{"analyses": [{"id": "6a9eed4d-bda9-4cd4-8b07-60f0e742ecc5", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T18:21:19.647200", "filename": "xray report .jpg"}, {"id": "67da50e5-17cf-4db5-98b3-aa09151ef7e9", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T22:56:25.819616", "filename": "xray report .jpg"}, {"id": "4bf693c3-5a93-4f64-9ccb-7b7efc4d9f1f", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T23:04:54.111855", "filename": "xray report .jpg"}, {"id": "df2eef21-45b7-46f3-8318-c843853ebfc9", "analysis": "Error analyzing image: Error code: 401 - {'error': {'message': 'Incorrect API key provided: hf_uUUii*************************oDqg. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}", "findings": [], "keywords": [], "date": "2025-04-20T23:27:18.399745", "filename": "xray report .jpg"}, {"id": "4055c285-18c0-45ae-a220-889a93257ae6", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T23:46:07.169416", "filename": "xray report .jpg"}, {"id": "55d39aae-eb03-4789-9eaa-ed84fb2e5217", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T23:51:23.883042", "filename": "xray report .jpg"}, {"id": "d1ca4a94-eec6-46f0-9a8d-a9391cf5a41f", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T23:55:46.983233", "filename": "xray report .jpg"}, {"id": "f35a071f-dfe5-4974-8ed2-3d471d0eaade", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-20T23:56:40.328342", "filename": "xray report .jpg"}, {"id": "4bbca081-bb39-4482-8d01-d12c32bb4856", "analysis": "Error analyzing image: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}", "findings": [], "keywords": [], "date": "2025-04-21T00:04:17.464805", "filename": "xray report .jpg"}, {"id": "789b4390-3a9b-4be8-9ca7-5301ba1a9dfd", "analysis": "Error analyzing image: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}", "findings": [], "keywords": [], "date": "2025-04-21T00:13:59.980487", "filename": "xray report .jpg"}, {"id": "2ade0d84-1f20-4353-94b0-06e3ff2708ee", "analysis": "Error analyzing image: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}", "findings": [], "keywords": [], "date": "2025-04-21T00:25:45.067419", "filename": "xray report .jpg"}]}